version: "3"

services:
  db:
    image: postgres:16.0
    volumes:
      - greenapple_db:/var/lib/postgresql/data
    env_file:
      - src/core/config/.env
    ports:
      - "5432:5432"
    networks:
      - greenapple-network
    container_name: greenapple-db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  back:
    build: .
    command: bash start_app.sh
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    networks:
      - greenapple-network
    depends_on:
      db:
        condition: service_healthy
    container_name: greenapple-back
    restart: always

networks:
  greenapple-network:

volumes:
  greenapple_db:
