version: "3"

services:
  db:
    image: postgres:16.0
    volumes:
      - greenapple_db:/var/lib/postgresql/data
    env_file:
      - src/core/config/.env
    ports:
      - "5432:5432"
    networks:
      - greenapple-network
    container_name: greenapple-db

  back:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    networks:
      - greenapple-network
    depends_on:
      - db
    container_name: greenapple-back
    restart: always

networks:
  greenapple-network:

volumes:
  greenapple_db:
