"""Add phone and password field to master table

Revision ID: 011e17e87e8a
Revises: a1e41fe8096b
Create Date: 2023-10-16 12:32:10.034849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011e17e87e8a'
down_revision: Union[str, None] = 'a1e41fe8096b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('masters', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'password')
    op.drop_column('masters', 'phone')
    # ### end Alembic commands ###
