"""Добавить таблицу изменения статусов заказа.

Revision ID: 1dc24646fdc4
Revises: 9d51c7535b5c
Create Date: 2024-01-18 12:46:05.545952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc24646fdc4'
down_revision: Union[str, None] = '9d51c7535b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_changed_table',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('repair_order_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('repair_orders_master_id_fkey', 'repair_orders', type_='foreignkey')
    op.drop_column('repair_orders', 'master_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_orders', sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('repair_orders_master_id_fkey', 'repair_orders', 'masters', ['master_id'], ['id'])
    op.drop_table('status_changed_table')
    # ### end Alembic commands ###
