"""Добавить модель заказа

Revision ID: 2b95d3d437ff
Revises: ef191996a89b
Create Date: 2023-12-24 18:35:54.228433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b95d3d437ff'
down_revision: Union[str, None] = 'ef191996a89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_orders',
    sa.Column('customer_full_name', sa.String(), nullable=False),
    sa.Column('customer_phone_number', sa.String(), nullable=False),
    sa.Column('phone_model', sa.String(), nullable=False),
    sa.Column('imei', sa.String(), nullable=False),
    sa.Column('defect', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_orders')
    # ### end Alembic commands ###
