"""Обновить значения по умолчанию для created_at и updated_at

Revision ID: 389f7b6bd0ba
Revises: dd58cbc4316e
Create Date: 2024-02-05 18:11:13.620227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389f7b6bd0ba'
down_revision: Union[str, None] = 'dd58cbc4316e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
