"""Добавить связь ONEtoMANY между мастером и заказом на ремонт

Revision ID: 63373c71619e
Revises: 9574464312e8
Create Date: 2023-12-24 20:33:55.358154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63373c71619e'
down_revision: Union[str, None] = '9574464312e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repair_orders', 'master_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repair_orders', 'master_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
