"""Добавить связь ONEtoMANY между мастером и заказом на ремонт

Revision ID: 9574464312e8
Revises: a07ce007b255
Create Date: 2023-12-24 20:32:56.590198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9574464312e8'
down_revision: Union[str, None] = 'a07ce007b255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_orders', sa.Column('master_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repair_orders', 'masters', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repair_orders', type_='foreignkey')
    op.drop_column('repair_orders', 'master_id')
    # ### end Alembic commands ###
