"""Добавить поле статуса

Revision ID: 9d51c7535b5c
Revises: 63373c71619e
Create Date: 2023-12-25 17:45:27.950936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d51c7535b5c'
down_revision: Union[str, None] = '63373c71619e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_orders', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_orders', 'status')
    # ### end Alembic commands ###
