"""Удалить поле track_number из модели заказов

Revision ID: a07ce007b255
Revises: f68659c83237
Create Date: 2023-12-24 19:31:58.837007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07ce007b255'
down_revision: Union[str, None] = 'f68659c83237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_orders', 'track_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_orders', sa.Column('track_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
