"""create master table

Revision ID: a1e41fe8096b
Revises: e997744bc4fe
Create Date: 2023-10-11 20:27:04.463339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e41fe8096b'
down_revision: Union[str, None] = 'e997744bc4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('name', sa.String(), nullable=False))
    op.add_column('masters', sa.Column('surname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'surname')
    op.drop_column('masters', 'name')
    # ### end Alembic commands ###
