"""Добавить поле статуса для таблицы изменения статуса

Revision ID: dd58cbc4316e
Revises: 1dc24646fdc4
Create Date: 2024-01-18 13:35:51.614998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd58cbc4316e'
down_revision: Union[str, None] = '1dc24646fdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_changed_table', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status_changed_table', 'status')
    # ### end Alembic commands ###
