"""Add salt column to masters table

Revision ID: ef191996a89b
Revises: 74336094a84e
Create Date: 2023-10-16 13:34:43.753189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef191996a89b'
down_revision: Union[str, None] = '74336094a84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('salt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'salt')
    # ### end Alembic commands ###
