"""Добавить поле track_number к модели заказов

Revision ID: f68659c83237
Revises: 2b95d3d437ff
Create Date: 2023-12-24 18:52:56.435247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68659c83237'
down_revision: Union[str, None] = '2b95d3d437ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_orders', sa.Column('track_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_orders', 'track_number')
    # ### end Alembic commands ###
